"""Regenerate the generated include lists.

The lab book and the work log are both strictly chronological, so their include
order is a fact about the directory, not something to maintain by hand:

    labbook/entries/YYYY-MM-DD-slug.tex  ->  labbook/entries.tex
    log/weekly/YYYY-Www.tex              ->  log/weeks.tex

    pixi run entries
    python3 scripts/doc_research/build_entries.py

TEMPLATE FILE — replaced on update. Stdlib only, on purpose: this must run in
any checkout without installing anything.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

ENTRY_DIR = ROOT / "labbook" / "entries"
ENTRY_INCLUDES = ROOT / "labbook" / "entries.tex"
ENTRY_NAME = re.compile(r"^(\d{4})-(\d{2})-(\d{2})-([a-z0-9][a-z0-9-]*)\.tex$")

WEEK_DIR = ROOT / "log" / "weekly"
WEEK_INCLUDES = ROOT / "log" / "weeks.tex"
WEEK_NAME = re.compile(r"^(\d{4})-W(\d{2})\.tex$")

HEADER_KEYS = ["ENTRY-DATE", "ENTRY-TITLE", "ENTRY-SUMMARY"]
WEEK_HEADER_KEYS = ["WEEK-ID", "WEEK-RANGE"]

GENERATED_BANNER = (
    "% GENERATED by scripts/doc_research/build_entries.py — do not edit by hand.\n"
    "% Rebuild with: pixi run entries\n"
)


@dataclass
class Entry:
    """One chronological file, with whatever metadata its header carries."""

    path: Path
    sort_key: str
    header: dict[str, str]

    @property
    def rel(self) -> str:
        return self.path.relative_to(ROOT).as_posix()

    @property
    def include_path(self) -> str:
        return self.rel[: -len(".tex")]

    def title(self) -> str:
        return self.header.get("ENTRY-TITLE") or self.header.get("WEEK-ID") or self.path.stem


def read_header(path: Path) -> dict[str, str]:
    """Parse the leading `% KEY: value` comment block of a .tex file."""
    header: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if not stripped.startswith("%"):
            break
        match = re.match(r"^%\s*([A-Z][A-Z-]*)\s*:\s*(.+?)\s*$", stripped)
        if match:
            header.setdefault(match.group(1), match.group(2))
    return header


def entries() -> list[Entry]:
    """Lab book entries, oldest first. Same date sorts by slug."""
    found = []
    if ENTRY_DIR.is_dir():
        for path in sorted(ENTRY_DIR.glob("*.tex")):
            if ENTRY_NAME.match(path.name):
                found.append(Entry(path, path.name, read_header(path)))
    return found


def weeks() -> list[Entry]:
    """Weekly summaries, oldest first."""
    found = []
    if WEEK_DIR.is_dir():
        for path in sorted(WEEK_DIR.glob("*.tex")):
            if WEEK_NAME.match(path.name):
                found.append(Entry(path, path.name, read_header(path)))
    return found


def render(items: list[Entry], what: str) -> str:
    lines = [GENERATED_BANNER]
    if not items:
        lines.append(f"\n% No {what} yet.\n")
    else:
        lines.append("\n")
        lines.extend(f"\\include{{{item.include_path}}}\n" for item in items)
    return "".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    """Write only on a real change, so nothing is touched needlessly."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def up_to_date() -> list[str]:
    """Names of the include files that would change if rebuilt."""
    stale = []
    for path, content in (
        (ENTRY_INCLUDES, render(entries(), "entries")),
        (WEEK_INCLUDES, render(weeks(), "weekly summaries")),
    ):
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(path.relative_to(ROOT).as_posix())
    return stale


def main() -> int:
    changed = []
    if write_if_changed(ENTRY_INCLUDES, render(entries(), "entries")):
        changed.append(ENTRY_INCLUDES.relative_to(ROOT).as_posix())
    if write_if_changed(WEEK_INCLUDES, render(weeks(), "weekly summaries")):
        changed.append(WEEK_INCLUDES.relative_to(ROOT).as_posix())
    if changed:
        print("rebuilt: " + ", ".join(changed))
    else:
        print("include lists already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
